name: Swift

on:
  push:
    branches: [ feat/v2/develop ]
  pull_request:
    branches: [ feat/v2/develop ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
     matrix:
      swift-version: [5.2.0]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

